---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbdeploy
  labels:
    app: facebook
spec:
  selector:
    matchLabels:
      app: facebook 
  replicas: 2 
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
    spec:
      containers:
        - name: fbcont
          image: devopshubg333/batch14:5
          ports:
            - containerPort: 8080

